// <auto-generated />
using System;
using AISEA.ApiService.DAL.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AISEA.ApiService.DAL.Migrations
{
    [DbContext(typeof(AiseaContext))]
    [Migration("20250821152611_removeCourseTrackLVOptionalSubject")]
    partial class removeCourseTrackLVOptionalSubject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.AdvisorySession1to1", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StaffJoinAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StudentJoinAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("advisorysession1to1_id_primary");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AdvisorySession1to1_CreatedAt");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("IX_AdvisorySession1to1_StaffId");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_AdvisorySession1to1_StudentId");

                    b.ToTable("AdvisorySession1to1");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(20000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccessAction")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("auditlog_id_primary");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.BookedMeeting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CheckInCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Feedback")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StaffProfileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("StudentProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("SuggestionFromAdvisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleStudentIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("bookedmeeting_id_primary");

                    b.HasIndex("StaffProfileId");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("BookedMeeting", t =>
                        {
                            t.HasTrigger("TR_BookedMeeting_AntiStudentSpamCancel");

                            t.HasTrigger("TR_BookedMeeting_CheckExternalTables");

                            t.HasTrigger("TR_BookedMeeting_CheckInternalData");

                            t.HasTrigger("TR_BookedMeeting_PreventStudentTooManyPending");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.BookingAvailability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayInWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<long>("StaffProfileId")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("bookingavailability_id_primary");

                    b.HasIndex("StaffProfileId", "DayInWeek", "StartTime", "EndTime")
                        .IsUnique()
                        .HasDatabaseName("IX_BookingAvailability_UniqueTimeSlot");

                    b.ToTable("BookingAvailability", t =>
                        {
                            t.HasTrigger("TR_BookingAvailability_CheckOverlap");

                            t.HasCheckConstraint("CK_BookingAvailability_EndTime", "[EndTime] > [StartTime]");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Combo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComboDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComboName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("combo_id_primary");

                    b.ToTable("Combo");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.ComboSubject", b =>
                {
                    b.Property<long>("ComboId")
                        .HasColumnType("bigint")
                        .HasColumnName("combo_id");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ComboId", "SubjectId")
                        .HasName("combosubject_composite_primary");

                    b.HasIndex("ComboId")
                        .HasDatabaseName("IX_ComboSubject_ComboId");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_ComboSubject_SubjectId");

                    b.ToTable("ComboSubject");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Curriculum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurriculumCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurriculumName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("EffectiveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("curriculum_id_primary");

                    b.HasIndex("CurriculumCode")
                        .IsUnique()
                        .HasDatabaseName("curriculum_code_unique");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("IX_Curriculum_ProgramId");

                    b.HasIndex(new[] { "CurriculumCode" }, "curriculum_code_unique")
                        .IsUnique();

                    b.ToTable("Curriculum");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.CurriculumSubject", b =>
                {
                    b.Property<long>("CurriculumId")
                        .HasColumnType("bigint")
                        .HasColumnName("curriculum_id");

                    b.Property<long>("SubjectVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_version_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CurriculumId", "SubjectVersionId")
                        .HasName("curriculumsubject_composite_primary");

                    b.HasIndex("CurriculumId")
                        .HasDatabaseName("IX_CurriculumSubject_CurriculumId");

                    b.HasIndex("SubjectVersionId")
                        .HasDatabaseName("IX_CurriculumSubject_SubjectVersionId");

                    b.ToTable("CurriculumSubject");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.JoinedSubject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("GithubRepositoryURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SemesterId")
                        .HasColumnType("bigint");

                    b.Property<int>("SemesterStudyBlockType")
                        .HasColumnType("int");

                    b.Property<long>("StudentProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectVersionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("joinedsubject_id_primary");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentProfileId", "SemesterId", "SemesterStudyBlockType", "SubjectCode")
                        .IsUnique()
                        .HasDatabaseName("UX_JoinedSubject_Student_Semester_BlockType_Subject");

                    b.ToTable("JoinedSubject", t =>
                        {
                            t.HasTrigger("trg_JoinedSubject_SubjectCode_Limit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.JoinedSubjectCheckPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<long>("JoinedSubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Link1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("joinedsubjectcheckpoint_id_primary");

                    b.HasIndex("JoinedSubjectId");

                    b.ToTable("JoinedSubjectCheckPoint", (string)null);
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.LeaveSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("StaffProfileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("leaveschedule_id_primary");

                    b.HasIndex("StaffProfileId", "StartDateTime", "EndDateTime")
                        .IsUnique()
                        .HasDatabaseName("IX_LeaveSchedule_UniqueSchedule");

                    b.ToTable("LeaveSchedule", t =>
                        {
                            t.HasTrigger("TR_LeaveSchedule_CheckConstraints");

                            t.HasCheckConstraint("CK_LeaveSchedule_WithinSingleDay", "CAST([StartDateTime] AS date) = CAST([EndDateTime] AS date)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AdvisorySession1to1Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("message_id_primary");

                    b.HasIndex("AdvisorySession1to1Id")
                        .HasDatabaseName("IX_Message_AdvisorySession1to1Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Message_CreatedAt");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("IX_Message_SenderId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("notification_id_primary");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Program", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("program_id_primary");

                    b.HasIndex("ProgramCode")
                        .IsUnique()
                        .HasDatabaseName("program_code_unique");

                    b.ToTable("Program");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("role_id_primary");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("role_name_unique");

                    b.HasIndex(new[] { "Name" }, "role_name_unique")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Semester", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("semester_id_primary");

                    b.HasIndex("SemesterName")
                        .IsUnique()
                        .HasDatabaseName("IX_Semester_SemesterName_Unique");

                    b.ToTable("Semester");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SessionOutcomeMapping", b =>
                {
                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<long>("OutcomeId")
                        .HasColumnType("bigint")
                        .HasColumnName("outcome_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionId", "OutcomeId")
                        .HasName("sessionoutcomemapping_composite_primary");

                    b.HasIndex("OutcomeId")
                        .HasDatabaseName("IX_SessionOutcomeMapping_OutcomeId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_SessionOutcomeMapping_SessionId");

                    b.ToTable("SessionOutcomeMapping");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.StaffProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("EndWorkAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("StartWorkAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("staffprofile_id_primary");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_StaffProfile_UserId");

                    b.ToTable("StaffProfile");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.StudentProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CareerGoal")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurriculumCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DoGraduate")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfBan")
                        .HasColumnType("int");

                    b.Property<long?>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<string>("RegisteredComboCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("studentprofile_id_primary");

                    b.HasIndex("ProgramId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_StudentProfile_UserId");

                    b.ToTable("StudentProfile");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.StudyRoadMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StudentProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("studyroadmap_id_primary");

                    b.HasIndex("StudentProfileId")
                        .IsUnique();

                    b.ToTable("StudyRoadMap");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.StudyRoadMapNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.Property<long>("StudyRoadMapId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("studyroadmapnode_id_primary");

                    b.HasIndex("StudyRoadMapId");

                    b.ToTable("StudyRoadMapNodes");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("subject_id_primary");

                    b.HasIndex("SubjectCode")
                        .IsUnique()
                        .HasDatabaseName("subject_code_unique");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SubjectMarkReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("JoinedSubjectId")
                        .HasColumnType("bigint");

                    b.Property<double>("MinScore")
                        .HasColumnType("float");

                    b.Property<string>("ScoreUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("subjectmarkreport_id_primary");

                    b.HasIndex("JoinedSubjectId");

                    b.ToTable("SubjectMarkReport", (string)null);
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SubjectVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "VersionCode")
                        .IsUnique();

                    b.ToTable("SubjectVersion", (string)null);
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SubjectVersionPrerequisite", b =>
                {
                    b.Property<long>("SubjectVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_version_id");

                    b.Property<long>("PrerequisiteSubjectVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("prerequisite_subject_version_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubjectVersionId", "PrerequisiteSubjectVersionId")
                        .HasName("subjectversionprerequisite_composite_primary");

                    b.HasIndex("PrerequisiteSubjectVersionId")
                        .HasDatabaseName("IX_SubjectVersionPrerequisite_PrerequisiteSubjectVersionId");

                    b.HasIndex("SubjectVersionId")
                        .HasDatabaseName("IX_SubjectVersionPrerequisite_SubjectVersionId");

                    b.ToTable("SubjectVersionPrerequisite", (string)null);
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Syllabus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SubjectVersionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("syllabus_id_primary");

                    b.HasIndex("SubjectVersionId")
                        .HasDatabaseName("IX_Syllabus_SubjectVersionId");

                    b.ToTable("Syllabus");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SyllabusAssessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompletionCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("SyllabusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id")
                        .HasName("syllabusassessment_id_primary");

                    b.HasIndex("SyllabusId")
                        .HasDatabaseName("IX_SyllabusAssessment_SyllabusId");

                    b.ToTable("SyllabusAssessment");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SyllabusLearningMaterial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthorName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilepathOrUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("PublishedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("SyllabusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("syllabuslearningmaterial_id_primary");

                    b.HasIndex("SyllabusId")
                        .HasDatabaseName("IX_SyllabusLearningMaterial_SyllabusId");

                    b.ToTable("SyllabusLearningMaterial");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SyllabusLearningOutcome", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OutcomeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("SyllabusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("syllabuslearningoutcome_id_primary");

                    b.HasIndex("SyllabusId")
                        .HasDatabaseName("IX_SyllabusLearningOutcome_SyllabusId");

                    b.ToTable("SyllabusLearningOutcome");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SyllabusSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int");

                    b.Property<long>("SyllabusId")
                        .HasColumnType("bigint");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("syllabussession_id_primary");

                    b.HasIndex("SyllabusId")
                        .HasDatabaseName("IX_SyllabusSession_SyllabusId");

                    b.ToTable("SyllabusSession");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("user_id_primary");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("user_email_unique");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_User_RoleId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("user_username_unique");

                    b.HasIndex(new[] { "Email" }, "user_email_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "user_username_unique")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.AdvisorySession1to1", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.StaffProfile", "Staff")
                        .WithMany("AdvisorySessions1to1")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("advisorysession1to1_staffid_foreign");

                    b.HasOne("AISEA.ApiService.DAL.Entities.StudentProfile", "Student")
                        .WithMany("AdvisorySessions1to1")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("advisorysession1to1_studentid_foreign");

                    b.Navigation("Staff");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.BookedMeeting", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.StaffProfile", "StaffProfile")
                        .WithMany("BookedMeetings")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookedmeeting_staffprofileid_foreign");

                    b.HasOne("AISEA.ApiService.DAL.Entities.StudentProfile", "StudentProfile")
                        .WithMany("BookedMeetings")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookedmeeting_studentprofileid_foreign");

                    b.Navigation("StaffProfile");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.BookingAvailability", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.StaffProfile", "StaffProfile")
                        .WithMany("BookingAvailabilities")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bookingavailability_staffprofileid_foreign");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.ComboSubject", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.Combo", "Combo")
                        .WithMany("ComboSubjects")
                        .HasForeignKey("ComboId")
                        .IsRequired()
                        .HasConstraintName("combosubject_comboid_foreign");

                    b.HasOne("AISEA.ApiService.DAL.Entities.Subject", "Subject")
                        .WithMany("ComboSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("combosubject_subjectid_foreign");

                    b.Navigation("Combo");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Curriculum", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.Program", "Program")
                        .WithMany("Curricula")
                        .HasForeignKey("ProgramId")
                        .IsRequired()
                        .HasConstraintName("curriculum_program_foreign");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.CurriculumSubject", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.Curriculum", "Curriculum")
                        .WithMany("CurriculumSubjects")
                        .HasForeignKey("CurriculumId")
                        .IsRequired()
                        .HasConstraintName("curriculumsubject_curriculumid_foreign");

                    b.HasOne("AISEA.ApiService.DAL.Entities.SubjectVersion", "SubjectVersion")
                        .WithMany("CurriculumSubjects")
                        .HasForeignKey("SubjectVersionId")
                        .IsRequired()
                        .HasConstraintName("curriculumsubject_subjectversionid_foreign");

                    b.Navigation("Curriculum");

                    b.Navigation("SubjectVersion");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.JoinedSubject", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.Semester", "Semester")
                        .WithMany("JoinedCourses")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("joinedcourse_semesterid_foreign");

                    b.HasOne("AISEA.ApiService.DAL.Entities.StudentProfile", "StudentProfile")
                        .WithMany("JoinedCourses")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("joinedsubject_studentprofileid_foreign");

                    b.Navigation("Semester");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.JoinedSubjectCheckPoint", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.JoinedSubject", "JoinedSubject")
                        .WithMany("JoinedSubjectCheckPoints")
                        .HasForeignKey("JoinedSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("joinedsubjectcheckpoint_joinedsubjectid_foreign");

                    b.Navigation("JoinedSubject");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.LeaveSchedule", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.StaffProfile", "StaffProfile")
                        .WithMany("LeaveSchedules")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("leaveschedule_staffprofileid_foreign");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Message", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.AdvisorySession1to1", "AdvisorySession1to1")
                        .WithMany("Messages")
                        .HasForeignKey("AdvisorySession1to1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_advisorysession1to1id_foreign");

                    b.HasOne("AISEA.ApiService.DAL.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_senderid_foreign");

                    b.Navigation("AdvisorySession1to1");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Notification", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("notification_userid_foreign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SessionOutcomeMapping", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.SyllabusLearningOutcome", "Outcome")
                        .WithMany("SessionOutcomeMappings")
                        .HasForeignKey("OutcomeId")
                        .IsRequired()
                        .HasConstraintName("sessionoutcomemapping_outcomeid_foreign");

                    b.HasOne("AISEA.ApiService.DAL.Entities.SyllabusSession", "Session")
                        .WithMany("SessionOutcomeMappings")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("sessionoutcomemapping_sessionid_foreign");

                    b.Navigation("Outcome");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.StaffProfile", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.User", "User")
                        .WithOne("StaffProfile")
                        .HasForeignKey("AISEA.ApiService.DAL.Entities.StaffProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("staffprofile_userid_foreign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.StudentProfile", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.Program", "Program")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("studentprofile_programid_foreign");

                    b.HasOne("AISEA.ApiService.DAL.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("AISEA.ApiService.DAL.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("studentprofile_userid_foreign");

                    b.Navigation("Program");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.StudyRoadMap", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.StudentProfile", "StudentProfile")
                        .WithOne("StudyRoadMap")
                        .HasForeignKey("AISEA.ApiService.DAL.Entities.StudyRoadMap", "StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("studyroadmap_studentprofileid_foreign");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.StudyRoadMapNode", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.StudyRoadMap", "StudyRoadMap")
                        .WithMany("Nodes")
                        .HasForeignKey("StudyRoadMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("studyroadmapnode_studyroadmapid_foreign");

                    b.Navigation("StudyRoadMap");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SubjectMarkReport", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.JoinedSubject", "JoinedSubject")
                        .WithMany("SubjectMarkReports")
                        .HasForeignKey("JoinedSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("subjectmarkreport_joinedsubjectid_foreign");

                    b.Navigation("JoinedSubject");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SubjectVersion", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.Subject", "Subject")
                        .WithMany("SubjectVersions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SubjectVersionPrerequisite", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.SubjectVersion", "PrerequisiteSubjectVersion")
                        .WithMany("DependentSubjectVersions")
                        .HasForeignKey("PrerequisiteSubjectVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("subjectversionprerequisite_prerequisitesubjectversionid_foreign");

                    b.HasOne("AISEA.ApiService.DAL.Entities.SubjectVersion", "SubjectVersion")
                        .WithMany("Prerequisites")
                        .HasForeignKey("SubjectVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("subjectversionprerequisite_subjectversionid_foreign");

                    b.Navigation("PrerequisiteSubjectVersion");

                    b.Navigation("SubjectVersion");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Syllabus", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.SubjectVersion", "SubjectVersion")
                        .WithMany("Syllabi")
                        .HasForeignKey("SubjectVersionId")
                        .IsRequired()
                        .HasConstraintName("syllabus_subjectversionid_foreign");

                    b.Navigation("SubjectVersion");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SyllabusAssessment", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.Syllabus", "Syllabus")
                        .WithMany("SyllabusAssessments")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("syllabusassessment_syllabusid_foreign");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SyllabusLearningMaterial", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.Syllabus", "Syllabus")
                        .WithMany("SyllabusLearningMaterials")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("syllabuslearningmaterial_syllabusid_foreign");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SyllabusLearningOutcome", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.Syllabus", "Syllabus")
                        .WithMany("SyllabusLearningOutcomes")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("syllabuslearningoutcome_syllabusid_foreign");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SyllabusSession", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.Syllabus", "Syllabus")
                        .WithMany("SyllabusSessions")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("syllabussession_syllabusid_foreign");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.User", b =>
                {
                    b.HasOne("AISEA.ApiService.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_roleid_foreign");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.AdvisorySession1to1", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Combo", b =>
                {
                    b.Navigation("ComboSubjects");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Curriculum", b =>
                {
                    b.Navigation("CurriculumSubjects");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.JoinedSubject", b =>
                {
                    b.Navigation("JoinedSubjectCheckPoints");

                    b.Navigation("SubjectMarkReports");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Program", b =>
                {
                    b.Navigation("Curricula");

                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Semester", b =>
                {
                    b.Navigation("JoinedCourses");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.StaffProfile", b =>
                {
                    b.Navigation("AdvisorySessions1to1");

                    b.Navigation("BookedMeetings");

                    b.Navigation("BookingAvailabilities");

                    b.Navigation("LeaveSchedules");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.StudentProfile", b =>
                {
                    b.Navigation("AdvisorySessions1to1");

                    b.Navigation("BookedMeetings");

                    b.Navigation("JoinedCourses");

                    b.Navigation("StudyRoadMap");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.StudyRoadMap", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Subject", b =>
                {
                    b.Navigation("ComboSubjects");

                    b.Navigation("SubjectVersions");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SubjectVersion", b =>
                {
                    b.Navigation("CurriculumSubjects");

                    b.Navigation("DependentSubjectVersions");

                    b.Navigation("Prerequisites");

                    b.Navigation("Syllabi");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.Syllabus", b =>
                {
                    b.Navigation("SyllabusAssessments");

                    b.Navigation("SyllabusLearningMaterials");

                    b.Navigation("SyllabusLearningOutcomes");

                    b.Navigation("SyllabusSessions");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SyllabusLearningOutcome", b =>
                {
                    b.Navigation("SessionOutcomeMappings");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.SyllabusSession", b =>
                {
                    b.Navigation("SessionOutcomeMappings");
                });

            modelBuilder.Entity("AISEA.ApiService.DAL.Entities.User", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("StaffProfile");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
