version: '3.8'
services:
  aisea-api:
    build:
      context: ./AISEA.ApiService
      dockerfile: AISEA.ApiService.WebApi/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./AISEA.ApiService:/src
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisSettings__ConnectionString=${REDIS_CONNECTION_STRING}
      - SqlSettings__ConnectionString=${SQL_CONNECTION_STRING}

  aisea-worker:
    build:
      context: ./AISEA.BgService
      dockerfile: AISEA.BgService.Worker/Dockerfile
    volumes:
      - ./AISEA.BgService:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SqlSettings__ConnectionString=${SQL_CONNECTION_STRING}

