version: '3.8'
services:
  aisea-api:
    build:
      context: ./AISEA.ApiService
      dockerfile: AISEA.ApiService.WebApi/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./AISEA.ApiService:/src
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisSettings__ConnectionString=${REDIS_CONNECTION_STRING}
    depends_on:
      - aisea-worker
      - redis-server
    networks:
      - aisea-network

  aisea-worker:
    build:
      context: ./AISEA.BgService
      dockerfile: AISEA.BgService.Worker/Dockerfile
    volumes:
      - ./AISEA.BgService:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - aisea-network

  redis-server:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aisea-network

networks:
  aisea-network:
    driver: bridge
