namespace AISEA.ApiService.SHARED.Const.Enums;

public enum EAuditLogTag
{

    NONE,
    REMOVE_NOTI,
    REMOVE_CHATSESSION,
    GOOGLE_LOGIN,
    FEID_LOGIN,
    FORGET_PASSWORD,
    RESET_PASSWORD,
    CREATE_USER,
    DELETE_USER,
    DELETE_BOOKING_AVAILABILITY,
    CREATE_BOOKING_AVAILABILITY,
    UPDATE_BOOKING_AVAILABILITY


}