name: Docker Compose BE Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            # Stop and remove all containers except those with 'sql' or 'redis' in their name or image
            docker ps -a --format "{{.ID}} {{.Image}} {{.Names}}" | grep -v -i "sql\|redis" | awk '{print $1}' | xargs -r docker rm -f

            # Remove all images except those with 'sql' or 'redis' in their name
            docker images --format "{{.ID}} {{.Repository}}" | grep -v -i "sql\|redis" | awk '{print $1}' | xargs -r docker rmi -f

            # Disconnect all containers from aisea-network
            for container in $(docker network inspect aisea-network --format '{{range .Containers}}{{.Name}} {{end}}' 2>/dev/null); do
              docker network disconnect aisea-network $container || true
            done

            # Remove the existing aisea-network if it exists
            docker network rm aisea-network || true

            # Create a new aisea-network
            docker network create aisea-network

            # Connect existing redis-server and sqlserver containers to the new network
            docker network connect aisea-network redis-server || true
            docker network connect aisea-network sqlserver || true

            cd /home/official_deploy/main/Back-end
            git fetch origin
            git checkout main
            git pull
            docker-compose up --build -d